FROM node:latest

EXPOSE 3000

RUN npm i npm@latest -g
RUN npm i nodemon -g
RUN mkdir /opt/app && chown node:node /opt/app
WORKDIR /opt/app
USER node
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
CMD ["nodemon" ]